include = ["**/Cargo.toml"]
exclude = ["**/.venv/**"]

[formatting]
indent_string = "    "

[[rule]]
keys = ["workspace.dependencies", "dependencies", "dev-dependencies"]

[rule.formatting]
reorder_keys = true
