name: devcontainer

on:
  # trigger manually
  workflow_dispatch:

  # run automatically once a month to update
  # any changes in the base image
  schedule:
  - cron: "0 1 1 * *"

  # update on changes
  push:
    branches: [ main ]
    paths:
      - '.devcontainer/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: taiki-e/install-action@just
      - name: Publish
        run: just publish-dev-container "$(date +%Y%m%d)"
