name: hosted-post-merge_version_update

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Type of version bump
        type: choice
        options:
          - major
          - minor
          - patch
          - release
          - rc
          - beta
          - alpha
        required: true
        default: patch

env:
  CARGO_TERM_COLOR: always

jobs:
  versioning:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          git config --global user.email "info@thin-edge.io"
          git config --global user.name "Versioneer"

      - name: enable toolchain via github action
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.64.0
          components: cargo
          override: true

      - name: Enable cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-release
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version 0.24.4 cargo-release

      - name: Increment version and tag
        uses: actions-rs/cargo@v1
        with:
          command: release
          args: ${{ inputs.bump }} --no-publish --no-push --no-tag -vv --no-confirm --execute

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: ${{ inputs.bump }} version bump
          delete-branch: true
          title: ${{ inputs.bump }} version bump
          body: ${{ inputs.bump }} version bump
          reviewers: rina23q
