name: Pull Request Checks

on:
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  block-fixup:
    name: Block fixup commits
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Block Fixup Commit Merge
        # https://github.com/13rac1/block-fixup-merge-action
        uses: 13rac1/block-fixup-merge-action@v2.0.0

  # JOB to run change detection
  changes:
    name: Filter changes
    runs-on: Ubuntu-20.04
    # Set job outputs to values from filter step
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      rust: ${{ steps.filter.outputs.rust }}
      workflows: ${{ steps.filter.outputs.workflows }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        # https://github.com/dorny/paths-filter
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'
            rust:
              - 'crates/**'
              - 'plugins/**'
              - 'Cargo.*'
            workflows:
              - '.github/workflows/**'

  #
  # Checking that Cargo.lock is up to date
  #
  check-lockfile-uptodate:
    name: Check whether Cargo.lock is up to date
    runs-on: ubuntu-20.04
    outputs:
      locks: ${{ steps.filter.outputs.locks }}
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve MSRV from workspace Cargo.toml
        id: rust_version
        uses: SebRollen/toml-action@v1.0.2
        with:
          file: Cargo.toml
          field: "workspace.package.rust-version"

      - name: Enable toolchain via github action
        uses: dtolnay/rust-toolchain@master
        with:
          targets: armv7-unknown-linux-gnueabihf
          toolchain: ${{ steps.rust_version.outputs.value }}

      - uses: Swatinem/rust-cache@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            locks:
              - '**/Cargo.toml'

      - name: Check whether lockfile is up to date
        if: steps.filter.outputs.locks == 'true'
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked

  udeps:
    name: Check for unused dependencies
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' || needs.changes.outputs.workflows == 'true' }}
    steps:
      - uses: actions/checkout@v3

      - name: Install nightly toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - run: rustup override set ${{steps.toolchain.outputs.name}}

      - name: Run cargo-udeps
        uses: aig787/cargo-udeps-action@v1
        with:
          version: 'v0.1.35'
          args: '--all-features'

  mdbook-build-check:
    name: Run mdbook build
    runs-on: ubuntu-20.04
    needs: changes
    if: ${{ needs.changes.outputs.docs == 'true' || needs.changes.outputs.workflows == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        # https://github.com/marketplace/actions/mdbook-action
        with:
          mdbook-version: "0.4.18"

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install mdbook-mermaid
        uses: actions-rs/install@v0.1
        # https://github.com/marketplace/actions/rust-cargo-install
        with:
          crate: mdbook-mermaid
          version: latest

      - name: Install mdbook-linkcheck
        uses: actions-rs/install@v0.1
        # https://github.com/marketplace/actions/rust-cargo-install
        with:
          crate: mdbook-linkcheck
          version: latest

      - name: Install mdbook-admonish
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook-admonish
          version: latest

      - name: Install mdbook-pagetoc
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook-pagetoc
          version: latest

      - name: Install mdbook-cmdrun
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook-cmdrun
          version: latest

      - name: Cargo build tedge cli
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin tedge

      - name: Update PATH
        run: echo "$PWD/target/debug" >> $GITHUB_PATH

      - name: Run mdbook build
        shell: bash
        run: |
          echo "generating doc for $(tedge --version)"
          cd docs
          mdbook build

  cargo-sort:
    name: Run cargo sort
    runs-on: Ubuntu-20.04
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' || needs.changes.outputs.workflows == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cargo sort
        uses: actions-rs/install@v0.1
        # https://github.com/marketplace/actions/rust-cargo-install
        with:
          crate: cargo-sort
          version: latest

      - name: Cargo sort
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: sort
          args: -w . --check

  cargo-fmt:
    name: Run cargo fmt
    runs-on: Ubuntu-20.04
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' || needs.changes.outputs.workflows == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Nightly toolchain is needed for cargo fmt since issue: https://github.com/thin-edge/thin-edge.io/issues/1660
      # dtolnay/rust-toolchain is preferred over actions-rs/toolchain is currently not maintained and currently using
      # deprecated GHA api (see https://github.com/actions-rs/toolchain/issues/219).
      # However since dtolnay/rust-toolchain does not support the 'override' option, an additional call to
      # rustup override is required (see https://github.com/dtolnay/rust-toolchain/issues/29#issuecomment-1412903426)
      - name: Install nightly toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
      - run: rustup override set ${{steps.toolchain.outputs.name}}

      - name: Cargo fmt --version
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: fmt
          args: --version

      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: fmt
          args: -- --check

  cargo-clippy:
    name: Run cargo clippy
    runs-on: Ubuntu-20.04
    env:
      RUSTFLAGS: -D warnings
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' || needs.changes.outputs.workflows == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: enable toolchain via github action
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo clippy --version
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: clippy
          args: --version

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          toolchain: stable
          command: clippy
          args: --all-targets --all-features

  cargo-audit:
    name: Run cargo audit
    runs-on: Ubuntu-20.04
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' || needs.changes.outputs.workflows == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cargo audit
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: audit

  # Only run check if the project still compiles on MSRV, test are run on stable
  check-msrv:
    name: Run cargo check on MSRV
    runs-on: Ubuntu-20.04
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' || needs.changes.outputs.workflows == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Retrieve MSRV from workspace Cargo.toml
        id: rust_version
        uses: SebRollen/toml-action@v1.0.2
        with:
          file: Cargo.toml
          field: "workspace.package.rust-version"

      - name: Enable rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.rust_version.outputs.value }}

      - name: Enable cache
        uses: Swatinem/rust-cache@v2

      - name: Run `cargo check`
        run: cargo check --all-targets --all-features

  cargo-test:
    name: Run cargo test
    runs-on: Ubuntu-20.04
    env:
      RUSTFLAGS: -D warnings
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' || needs.changes.outputs.workflows == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Retrieve MSRV from workspace Cargo.toml
        id: rust_version
        uses: SebRollen/toml-action@v1.0.2
        with:
          file: Cargo.toml
          field: "workspace.package.rust-version"

      - name: Enable toolchain via github action
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Enable cache
        uses: Swatinem/rust-cache@v2

      - name: cargo install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: cargo llvm-cov
        run: cargo llvm-cov --no-fail-fast --locked --all-features --all-targets --codecov --output-path codecov.json

      # https://github.com/rust-lang/cargo/issues/6669
      - name: cargo test --doc
        run: cargo test --locked --all-features --doc

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master

  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: crate-ci/typos@v1.15.0
      continue-on-error: true
    - run: exit 0

  doc:
    runs-on: ubuntu-latest
    name: nightly / doc
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' || needs.changes.outputs.workflows == 'true' }}
    steps:
      - uses: actions/checkout@v3

      - name: Enable cache
        uses: Swatinem/rust-cache@v2

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo doc

        run: cargo doc --no-deps --all-features --workspace --exclude tedge_config_macros
